import csv

def read_data(filename):
    with open(filename, 'r', newline='') as file:
        reader = csv.reader(file)
        next(reader)
        data = [tuple(row) for row in reader]
    return data

def map_function(data, question_part):
    customer_id = data[0]
    product_category = data[1]
    purchase_amount = float(data[2])
    if question_part == 'a':
        return [(product_category, purchase_amount)]
    else:
        return [(customer_id, purchase_amount)]

def group_by(data):
    grouped_data = {}
    for key, value in data:
        if key not in grouped_data:
            grouped_data[key] = []
        grouped_data[key].append(value)
    return grouped_data.items()

def reduce_function(grouped_data):
    reduced_data = {}
    for key, values in grouped_data:
        total = sum(values)
        reduced_data[key] = total
    return reduced_data


# Read data from CSV file
input_data = read_data("purchase_records.csv")


# Part a
mapped_data_a = []
for entry in input_data:
    mapped_data_a.extend(map_function(entry, 'a'))
# print("\nData after Map Function: (for part a)")
# print(mapped_data_a[:10])

grouped_data_a = group_by(mapped_data_a)
# print("\nData after Group-By Function: (for part a)")
# print(grouped_data_a)

reduced_data_a = reduce_function(grouped_data_a)

# Print final result for part a
# Total revenue generated by each product category during the whole dataset period
for product_category, total_revenue in reduced_data_a.items():
    print("\nProduct Category:", product_category)
    print("Total Revenue:", total_revenue)

print('\n')

# Part b
mapped_data_b = []
for entry in input_data:
    mapped_data_b.extend(map_function(entry, 'b'))
# print("\nData after Map Function: (for part b)")
# print(mapped_data_b[:10])

grouped_data_b = group_by(mapped_data_b)
# print("\nData after Group-By Function: (for part b)")
# print(grouped_data_b)

reduced_data_b = reduce_function(grouped_data_b)

# Print final result for part b
# The most 10 popular customers in terms of their purchase volume
sorted_customers = sorted(reduced_data_b.items(), key=lambda x: x[1], reverse=True)
print("Top 10 Customers by Purchase Volume:")
for i, (customer_id, purchase_volume) in enumerate(sorted_customers[:10], 1):
    print(f"{i}. Customer ID: {customer_id}, Purchase Volume: ${purchase_volume}")